### ISSUE TITLE
Error -6

### ISSUE THREAD

**Issue by H0fi** [CINF/PyExpLabSys#11]
I am currently using a VSP300 with a slightly altered version of this code. So far i am able to connect to the machine. Unfortunately when i am using the function load_technique the error " -6 function failed" is returned. This is true for all techniques of the "test_bio_logic.py" file. 
Does anybody know the reason for that error or has a more detailed understanding of that error?

**Comment by KennethNielsen** [comment]
Hi @H0fi 

Its nice to hear that others are trying out the code. With regards to your problem, a few things pop to mind.

The potentiostats require special firmware to work with the DLL that this driver depends on. I remember thinking that the details around how to get that firmware on there was a little muddy. I highly recommend making sure that the correct firmware is loaded by trying to run one of the examples from the development package before trying out the Python driver.

Besides from firmware there are two places where things can differ and create problems:

The supported equipment is divided into two classes, the SP300 series (which includes yours) and the non SP300 series. This classification decides between two different technique files. To make sure that the correct technique file is loaded, you must make sure to instantiate driver correctly as described here: http://pyexplabsys.readthedocs.org/drivers_bio_logic.html#implement-a-new-potentiostat

That being said, as you can read in the module doc string or documentation (http://pyexplabsys.readthedocs.org/drivers_bio_logic.html#module-PyExpLabSys.drivers.bio_logic) the list of which equipment is in which category is not documented and had to be inferred from on of the examples. So if it fails with a SP300 series equipment, then simply try and instantiate it as a piece of equipment from the other category. There is a list of all equipment codes is knows in the `DEVICE_CODES` module constant and the list of which equipment is in the SP300 series in the `SP300SERIES` list.

The other thing that can go wrong is a 32 vs. 64 bit thing for the DLL, as you can see documented in the GeneralPotentiostat.__init__ docstring. If you think this gives problems, then you can give the class a path to the dll directly and try the other option. But given you description, I'm more inclined to think that it is the technique file issue.

BTW. Does the more basic stuff work. E.g. the things in the basic() test, because then it is almost certainly the technique file issue.

I would be happy to add a class for your equipment to the official repo or you can send me a pull request.

On another note, I'm really curious about where this driver would be used. Would you care to share a few details about yourself and the intended use?

**Comment by KennethNielsen** [comment]
Is there any new information to report. Did you make any progress?

**Comment by KennethNielsen** [comment]
Closing due to lack of feedback. Feel free to re-open if the issue persists.
