### ISSUE TITLE
Version 130 

### ISSUE THREAD

**Issue by AnastasiyaByelyakova** [CINF/PyExpLabSys#16]
Hello!
This work is very much impressive.
Would you mind sharing some ideas on changes needed 
to make it work with 130 version files? 
Thank you.

**Comment by KennethNielsen** [comment]
Hi @AnastasiyaByelyakova 

You will have to be a little more specific, since we have a lot of drivers and file parsers in here. However taking a wild guess it might be the Agilent file parser, correct?

**Comment by AnastasiyaByelyakova** [comment]
Oh,  sorry I was not clear. 
Yes, my question was about Agilent Chemstation .ch files parser.

**Comment by KennethNielsen** [comment]
Absolute. I would love to help. I'll re-acquaint myself with the code and get back you. May I ask how much experience with Python, binary formats and hex editors you have?

**Comment by AnastasiyaByelyakova** [comment]
Thank you so much! 
I have some experience with python, about 1,5 years. It did not included 
working with binary formats and hex editors. So this python aspect is new to me.

**Comment by KennethNielsen** [comment]
Hi

Ok, I have had a look at the code and if you are willing to do some of the work, then I can help you merge the changes and the support into PyExpLabSys.

You will need to have a .ch data file and an export of the same data file, so we know which metadata to look after.

If you look in the implementation of CHFile:

```python
# Constants used for binary file parsing
ENDIAN = '>'
STRING = ENDIAN + '{}s'
UINT8 = ENDIAN + 'B'
UINT16 = ENDIAN + 'H'
INT16 = ENDIAN + 'h'
INT32 = ENDIAN + 'i'


def parse_utf16_string(file_, encoding='UTF16'):
    """Parse a pascal type UTF16 encoded string from a binary file object"""
    # First read the expected number of CHARACTERS
    string_length = unpack(UINT8, file_.read(1))[0]
    # Then read and decode
    parsed = unpack(STRING.format(2 * string_length),
                    file_.read(2 * string_length))
    return parsed[0].decode(encoding)


class CHFile(object):
    """Class that implementats the Agilent .ch file format version 179"""

    # Fields is a table of name, offset and type. Types 'x-time' and 'utf16' are specially
    # handled, the rest are format arguments for struct unpack
    fields = (
        ('sequence_line_or_injection', 252, UINT16),
        ('injection_or_sequence_line', 256, UINT16),
        ('start_time', 282, 'x-time'),
        ('end_time', 286, 'x-time'),
        ('version_string', 326, 'utf16'),
        ('description', 347, 'utf16'),
        ('sample', 858, 'utf16'),
        ('operator', 1880, 'utf16'),
        ('date', 2391, 'utf16'),
        ('inlet', 2492, 'utf16'),
        ('instrument', 2533, 'utf16'),
        ('method', 2574, 'utf16'),
        ('software version', 3601, 'utf16'),
        ('software name', 3089, 'utf16'),
        ('software revision', 3802, 'utf16'),
        ('units', 4172, 'utf16'),
        ('detector', 4213, 'utf16'),
        ('yscaling', 4732, ENDIAN + 'd')
    )
    # The start position of the data
    data_start = 6144
    # The versions of the file format supported by this implementation
    supported_versions = {179}

```

, you can see a class variables named `fields`. This is basically a map of where in the header the different metadata is and what type it is. Below that is a marker of where the data starts. Multibyte types can have different ordering, which is why we need to mark the ordering, which is done with the endiannes. As you can see, these files use big endian ordering, so you will need to set your hex editor to that. After that, it is basically a matter of moving though the header with the hex editor and see whether any of the even numbered positions gives you a value in any of the types, that corresponds to a know value from the metadata.

If you have problems, I can probably help you get started, but then I will need a complete measurement from you.

**Comment by AnastasiyaByelyakova** [comment]
Thank you.
But it too late

**Comment by KennethNielsen** [comment]
Ok. I'll close this then. Re-open if it becomes relevant again.
